"""empty message

Revision ID: 699e2a9bb670
Revises: 264a749c6a25
Create Date: 2022-01-14 00:41:22.506966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699e2a9bb670'
down_revision = '264a749c6a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('balance', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
